import Head from "next/head";
import Cube from "../components/cube";
import Timer from "../components/Timer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cuber</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Timer></Timer>
        <Cube width={300} height={300}></Cube>
      </main>
    </div>
  );
}
